language: cpp

sudo: false

compiler:
 - gcc

os:
 - linux

cache:
  apt: true
  directories:
   - $HOME/deps

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  - mkdir -p "$HOME/deps"

  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - export BOOST_ROOT="$PWD/boost_1_58_0"
  - export GEOGRAPHICLIB_ROOT="$PWD/GeographicLib-1.37"
  - export CMAKE_GEOGRAPHICLIB_FLAGS="-DGeographicLib_INCLUDE_DIR=${GEOGRAPHICLIB_ROOT}/include -DGeographicLib_LIBRARY_RELEASE=${GEOGRAPHICLIB_ROOT}/src/.libs/libGeographic.so"
  - export CRYPTOPP_ROOT="$PWD/cryptopp-5.6.2"
  - export CMAKE_CRYPTOPP_FLAGS="-DCryptoPP_INCLUDE_DIR=${CRYPTOPP_ROOT}/install/include -DCryptoPP_LIBRARY=${CRYPTOPP_ROOT}/install/lib/libcryptopp.so"
  - export CMAKE_VERSION="3.1.3-Linux-x86_64"
  - export PATH="$PWD/cmake-${CMAKE_VERSION}/bin:$PATH"

  - travis/boost.sh
  - travis/cmake.sh
  - travis/cryptopp.sh
  - travis/geographiclib.sh

script:
  - mkdir -p "${HOME}/build"
  - pushd "${HOME}/build"
  - cmake -DBUILD_TESTS=ON ${CMAKE_GEOGRAPHICLIB_FLAGS} ${CMAKE_CRYPTOPP_FLAGS} ${TRAVIS_BUILD_DIR}
  - cmake --build .
  - ctest
  - popd
